#ifndef _DIP_DefConfig_hpp_
#define _DIP_DefConfig_hpp_

#define CONFIG_DIP_INLINE_PROXY
#define CONFIG_DIP_INLINE_GETTER
#define CONFIG_DIP_INLINE_SHORT
#define CONFIG_DIP_INLINE_MEDIUM
#define CONFIG_DIP_INLINE_LONG
#define CONFIG_DIP_SCALAR_TYPE_FLOAT

#endif
